### ISSUE TITLE
Is there a way to conditionally add flipper into expo app?

### ISSUE THREAD

**Issue by rlam3** [jakobo/expo-community-flipper#15]
Hi @jakobo 

Is there a way to conditionally add expo-community-flipper into the expo app based on environmental variables?

I'm trying to get Flipper to integrate only in development builds. And prevent Flipper from integrating into our app in staging or production. 

Thanks!

**Comment by thecodedrift** [comment]
Hi @rlam3, the feature you're looking for is the env value `FLIPPER_DISABLE=1` which is useful for CI, but can also be used for production builds.

> To disable Flipper in CI builds, set the env value of FLIPPER_DISABLE to 1. We specifically do not use the CI env value, as EAS identifies itself as a CI environment which would remove the ability to generate a development client containing flipper. Instead, the ENV value should be provided for your production builds.

**Comment by thecodedrift** [comment]
Linking issue: #9

**Comment by rlam3** [comment]
@jakobo Thank you! 

When you're talking about setting `FLIPPER_DISABLE=1`, are you referring to setting this inside of the build pipeline (ie. CircleCI) OR inside of expo.dev build pipeline as a secret?

**Comment by thecodedrift** [comment]
You can set it in a few places depending on how you're building:

 - In your app-build environment such as an EAS secret or in CircleCI's environment variables
 - In your `app.json` in a build profile specific to builds where you want Flipper disabled
 - In your build command when building `FLIPPER_DISABLE=1 expo build` (for legacy and standalone builds)
