### ISSUE TITLE
CommandError: Must specify "expo-platform" header or "platform" query parameter error

### ISSUE THREAD

**Issue by itsramiel** [jakobo/expo-community-flipper#24]
I was using it with expo sdk 45 and it was working well. I updated to expo sdk 46 and updates expo-community-flipper to 46.x.x. but flipper is not showing hermes debugger. 

I get the following error in the terminal: 
`CommandError: Must specify "expo-platform" header or "platform" query parameter`

I saw the pinned issue and it might be related but I honestly did not understand the fix.

```
System:
      OS: macOS(intel chip) 12.5.1
      Shell: 5.8.1 - /bin/zsh
```

**Comment by thecodedrift** [comment]
Thanks for the system info. I believe there's a bug in SDK 46 specifically with this header: https://github.com/expo/expo/issues/17495#issuecomment-1198802350

You can workaround it by calling expo start with the following command

`expo start --dev-client --force-manifest-type=classic`

**Comment by sporkl** [comment]
This was the top search result for this issue for me. In case anyone else winds up here, the above fix no longer works, but there's more up-to-date info here: https://github.com/expo/expo/issues/34107
