### ISSUE TITLE
Notice: iOS Flipper Known Compatibility Issues

### ISSUE THREAD

**Issue by thecodedrift** [jakobo/expo-community-flipper#27]
As of RN 0.69.2+ and Flipper 0.158.0, there are several issues with other config plugins that are incompatible with Flipper on iOS. This thread documents the known plugin / pod combinations with issues. Where possible, we try to link out to other threads to provide a complete picture of the problem.

### ❌  `expo-firebase-analytics`

Relevant Threads: #26

**reason** Firebase requires `use_frameworks` and is not compatible with Flipper at this time [1](https://github.com/invertase/react-native-firebase/issues/6425#issuecomment-1200297779), [2](https://github.com/invertase/react-native-firebase/issues/6332#issuecomment-1200260945), [3](https://github.com/facebook/flipper/issues/3861)

**resolution** If you do not believe you need `use_frameworks`, you may set the ECF plugin's `ios.stripUseFrameworks = true` which will ensure there are no `use_frameworks` lines in your podfile. However, other libraries may not build if you do this. Instead, we recommend turning _off_ Flipper on iOS by setting `ios.enabled = false` as this will still let you use Flipper for Android.

**Comment by Nsquik** [comment]
any updates on this? do you know when it will work with firebase?

**Comment by thecodedrift** [comment]
Hi @Nsquik. Unfortunately the use_frameworks + flipper is a known incompatibility that can't be worked around. The short explanation is that use_frameworks links common libraries such as Folly in a way which Flipper can no longer use. There are pretty complex workarounds with minimal success linked in the original post. (see: https://github.com/invertase/react-native-firebase/issues/6332)

If you absolutely need Flipper and Firebase, I suggest Mike's solution:

> It's going to be a while until it's all easy out of the box while this happens, until then v14 of this module is always available...

I'm sorry I don't have a better answer. :\
