### ISSUE TITLE
Idempotence

### ISSUE THREAD

**Issue by axeldelafosse** [jakobo/expo-community-flipper#3]
Hey Jakob!

Thank you for this config plugin! We started to use it for the Showtime app. Just wanted to note that the plugin doesn't seem to be idempotent-- we can't run `expo prebuild` multiple times:

```
✖ Config sync failed
[ios.dangerous]: withIosDangerousBaseMod: Cannot add Flipper to the project's ios/Podfile because it's malformed. Please report this with a copy of your project Podfile. You can generate this with the `expo prebuild` command.
```

Do you have the same issue?

**Comment by thecodedrift** [comment]
**Update** I spent the afternoon digging into the issue because I had some bandwidth. The [mergeContents function](https://github.com/expo/expo-cli/blob/main/packages/config-plugins/src/utils/generateCode.ts#L49) from expo is idempotent, indicating there might be other podfile changes we're not absorbing correctly.

Per the instructions, can you run `expo prebuild` locally and share your `Podfile`? It would appear the anchor we're using for flipper injection is missing.

1. There should be a `# Uncomment to opt-in to using Flipper` line in the Podfile, which is what we anchor off of
2. The `use_fipper!(...)` directive, should be flanked with expo config's generated headers. They look like this: `# @generated begin flipper - expo prebuild (DO NOT MODIFY) sync-...hash...` and `# @generated end flipper` respectively

If any of these conditions are false, we'll lose the idempotence and the config plugin should fail with the error above.  Let me know what's in your Podfile and we'll troubleshoot from there.

**Comment by axeldelafosse** [comment]
Thanks for digging into this! Here is the Podfile:

```
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

platform :ios, '12.0'

require 'json'
podfile_properties = JSON.parse(File.read('./Podfile.properties.json')) rescue {}

target 'Showtime' do
  use_expo_modules!
  config = use_native_modules!

  pod 'expo-dev-launcher', path: '../../../node_modules/expo-dev-launcher', :configurations => :debug
  pod 'expo-dev-menu', path: '../../../node_modules/expo-dev-menu', :configurations => :debug
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes'
  )

# @generated begin flipper - expo prebuild (DO NOT MODIFY) sync-c6ffa0efbab8489a66754399365c792c7e5fe18d
  use_flipper!()
# @generated end flipper
  # Uncomment to opt-in to using Flipper
  #
  # if !ENV['CI']
  #   use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  # end

  post_install do |installer|
    react_native_post_install(installer)

    # Workaround `Cycle inside FBReactNativeSpec` error for react-native 0.64
    # Reference: https://github.com/software-mansion/react-native-screens/issues/842#issuecomment-812543933
    installer.pods_project.targets.each do |target|
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end

end
```

**Comment by axeldelafosse** [comment]
The issue appears to be with

```
# @generated begin flipper - expo prebuild (DO NOT MODIFY) sync-c6ffa0efbab8489a66754399365c792c7e5fe18d
  use_flipper!()
# @generated end flipper
```

**Comment by thecodedrift** [comment]
I was able to track down the issue in expo config. The `mergeContents` result returns two properties:

* `didMerge` did the merge occur successfully
* `didClear` did the result clear successfully from a `removeContents` call

We rely on `didMerge` to tell us if the config was merged successfully. However, that property doesn't reflect if the merge wasn't required. To make it idempotent, we'll explicitly remove the generated content and then readd. I'll open a separate issue in the expo-cli repo for that problem, but for now can at least ensure repeated runs work as expected.

**Comment by thecodedrift** [comment]
Fixed in **44.0.1**

**Comment by hirbod** [comment]
Just a curious question: why do you remove the content in first place?
When I build my own config-plugins, I just make a check if a merge is required and just don't throw if its already there and skip my merge function.

Maybe there is a good explanation why you went that path with check -> remove -> readd

**Comment by thecodedrift** [comment]
The simple answer was that the code merge utility doesn't offer an "is merged" option afaik. 

https://github.com/expo/expo-cli/blob/main/packages/config-plugins/src/utils/generateCode.ts

By doing the remove + add step, we use as much expo code as possible and hopefully minimize the number of breaking points in our regex based plugin.
