### ISSUE TITLE
SDK 48 - Merge Into Expo

### ISSUE THREAD

**Issue by thecodedrift** [jakobo/expo-community-flipper#41]
# Why

In its current form, this plugin relies heavily on regex based mods in order to function, which means with every new expo SDK (which means every react-native update (which means every `Podfile` change)), we need to recertify that this plugin works. It's a cumbersome process, and one that's probably better managed at the time we're changing the `Podfile`.

# How

The plan is to add the core Flipper functionality to [`expo-build-properties`](https://docs.expo.dev/versions/latest/sdk/build-properties/), enabling basic Flipper support via an official config plugin. Developers on expo can then include Flipper the same way that they would include something like react-native firebase: add the necessary modules via npm and then configure the build properties plugin.

In practice, the `expo-build-properties` configuration would look like

```json5
{
  "expo": {
    "plugins": [
      [
        "expo-build-properties",
        {
          "android": {
            "flipper": true // or a flipper version string such as "0.128.0"
          },
          "ios": {
            "flipper": true // or a flipper version string such as "0.128.0"
          }
        }
      ]
    ]
  }
}
```

The template `Podfile` used by expo during `expo prebuild` and EAS would use these new config plugin properties to enable additional features. This is a pattern already used by the properties plugin for enabling things such as `use_frameworks`.

* [x] Update expo-community-flipper to not perform podfile changes if suitable arguments for flipper exist inside of `use_react_native`.  This is already possible thanks to `IOS_HAS_FLIPPER_ARG` `/use_react_native!\([\s\S]*^\s*:flipper_configuration\s+=>/gm`. It's an impefect regex, but is good enough for the purpose of migrating from a community plugin to the build properties solution
* [x] Add additional properties & typings for expo-config-properties [branch & diff](https://github.com/expo/expo/compare/main...jakobo:expo:expo-build-plugins/flipper)
* [x] Add backward-compatible change to Podfile that supports upcoming properties (when this lands, it WILL disable flipper on iOS for those using the plugin because of the regex). However, what will happen is Flipper does _not_ get added by us, and we can simply emit a proper warning telling folks to migrate to the official supported config plugin
* [x] Release an SDK48 version of plugin that informs users to migrate to the official solution

With SDK 48, this module can be marked as deprecated, and we can start solving the problems together in the expo issue tracker, discussions, and discord.

# Risks & Mitigation

Simplifying the configuration does have a couple of risks. It's possible (though increasingly unlikely) that a major Flipper change adds burden to the Expo team. It's also possible that an underlying lib (ie Folly) goes off the rails and we create a flipper+SDK combo that simply doesn't work. Thankfully, not including the config values for `cfg.ios.flipper` would turn flipper off,

Flipper could create AppDelegate changes or other stuff outside of the scope of the config plugin. I'd propose we cross that bridge if it comes to it. All signs point to Flipper being available in react-native, and at least one known working version being in the react-native layer by default.

# FYSA

/cc @Kudo

**Comment by SimenB** [comment]
Nice!

Would this also mean we can somehow exclude flipper entirely for non-development builds? Currently, even if I exclude the config plugin, the iOS build fails (I assume because it does something fancy when finding `react-native-flipper` in `node_modules` or something. Is it the auto-linker's "fault"?).

**Comment by thecodedrift** [comment]
> Would this also mean we can somehow exclude flipper entirely for non-development builds?

That's the plan. In the same way the `use_frameworks` isn't exposed unless you've enabled the associated build property, flipper would only be enabled if the build property was enabled.
 
I've also split your comment into its own issue; that sounds like a bug if it's still being rolled into the app and blocking the build.

**Comment by thecodedrift** [comment]
Branch and diff: https://github.com/expo/expo/compare/main...jakobo:expo:expo-build-plugins/flipper

This is kind of a rough first pass at the expo SDK changes

* Plugin
  * Uses an `Omit<>` trick I learned a month or two ago for the typing that gives us typeahead for "known" strings while still allowing an arbitrary string type. Otherwise `"enabled" | "disabled" | string` is just a verbose way of writing `string`.
* iOS
  * ~~Changes `use_frameworks` to not be called unless the build property is explicitly set. Previously, it was calling `use_frameworks!` with nil linkage which would still create the conflict with flipper~~
  * Adds a local `expo_flipper` that starts in the explicit disabled state, and then optionally upgrades it to either `enabled` or a specific version string. It does not allow specifying RSpec, Folly, etc as that's well beyond the common use case
  * Adds a test that ensures you cannot have a `useFrameworks` and `flipper` set on the iOS config at the same time
* Android
  * Uses a safe `withGradleProperties` mod, applying the changes only if the flipper config for android is set, and only if it is set to "enabled"
  * Disabling flipper in Android is now a huge set of gradle changes, and its unlikely the FB or Flipper teams are going to ever have a flag like we have with Podfiles

Some references on how/why we need to make the Podfile changes the way we did:

* https://github.com/facebook/react-native/blob/main/scripts/react_native_pods.rb - how the arguments are read in to `use_react_native`
* https://github.com/facebook/react-native/blob/main/scripts/cocoapods/flipper.rb - turns out `FlipperConfiguration.*` is more complex than it appears at first glance

**Comment by Kudo** [comment]
wow, that's awesome! thanks for picking up this quickly! 

> Changes use_frameworks to not be called unless the build property is explicitly set. Previously, it was calling use_frameworks! with nil linkage which would still create the conflict with flipper

i think this is not quite true. as we have the tail `if` in
```
use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
```

**Comment by thecodedrift** [comment]
> i think this is not quite true. as we have the tail if in

Chatted with Kudo via discord, as he had a working ruby repl. The if statement properly nulifies the entire line (my original understanding was that it was a conditional for the linkage prop, which is incorrect in ruby). Will revert the changes tied to use_frameworks based on his feedback.

**edit** Branch updated, and changeset for use_frameworks removed.

**Comment by rlam3** [comment]
Is there any breaking chances to how a dev client is built moving forward? or can we still rely on the FLIPPER_DISABLED flag?

**Comment by thecodedrift** [comment]
@rlam3  To keep max backwards compatibility for the merge, I think it's worth keeping the `FIPPER_DISABLE` (deprecated and to remove in SDK49), but also support the semi-official `NO_FLIPPER` flag from the official Podfile template [ref](https://github.com/facebook/react-native/blob/5fda72f678fd656daaa3b988410f3b3a8701b7e4/template/ios/Podfile#L7).

This way we're trending towards matching the templates & code found through searching up issues here or on google.

**edit** Updated the branch with the config change for review: https://github.com/expo/expo/compare/main...jakobo:expo:expo-build-plugins/flipper#diff-f771467c60e6353ad16c2d884089d1203b9babb0002664af5328194029853f14R20

**Comment by nandorojo** [comment]
Would be good to add the official support to the README! I only knew about it from Twitter...

https://twitter.com/jakobo/status/1629531998262837249?s=20

Thanks for all your hard work @jakobo.

**Comment by thecodedrift** [comment]
I've got some time this week to get the release out. It'll be a readme change and then running `npm deprecate` on v48.x, plus updating & closing relevant tickets plus a pinned issue pointing to the new docs. 

Thanks for the nudge @nandorojo ❤️
