### ISSUE TITLE
iOS including Flipper When Plugin Not in app.json

### ISSUE THREAD

**Issue by thecodedrift** [jakobo/expo-community-flipper#42]
> Nice!
> 
> Would this also mean we can somehow exclude flipper entirely for non-development builds? Currently, even if I exclude the config plugin, the iOS build fails (I assume because it does something fancy when finding `react-native-flipper` in `node_modules` or something. Is it the auto-linker's "fault"?).

_Originally posted by @SimenB in https://github.com/jakobo/expo-community-flipper/issues/41#issuecomment-1307936421_

So that I can triage this, can you do the following?

1. Include your SDK version of expo, as well as if you're building locally or via EAS
2. Locally run `expo prebuild` and paste your `ios/Podfile` to this thread
3. Share your `app.json` or `app.config.js`. Redactions are OK. Specifically, the `plugins` section is most important for triage
4. Include any additional error messages that may help in triaging the issue

Thank you for reporting this @SimenB!

**Comment by SimenB** [comment]
Thanks for looking into it!

1. 46.0.16, EAS
2. https://gist.github.com/SimenB/3c8b9b24c1e2823f99044efcc4b4be75#file-podfile
3. https://gist.github.com/SimenB/3c8b9b24c1e2823f99044efcc4b4be75#file-app-config-ts (the eas profile we build with does _not_ include the `EAS_DEV_CLIENT` env variable)
4. https://gist.github.com/SimenB/3c8b9b24c1e2823f99044efcc4b4be75#file-build-log

EDIT: I have `react-native-flipper@0.173.0` in my `package.json`, which is not the same as the example in this repo - would that matter? I see the version in this repo is older and doesn't support react@18 (https://www.runpkg.com/?react-native-flipper@0.158.0/package.json#27), but maybe some version in the middle is more correct?

EDIT2: If it's autolinking, the docs is somewhat unfortunate on exclusion as it seems to be `package.json`-based (meaning 
 it's static): https://docs.expo.dev/modules/autolinking/#exclude

**Comment by thecodedrift** [comment]
This is really helpful. The version of `react-native-flipper` shouldn't matter, only that the one in your package.json matches the one you declare in your plugin config.

It appears that the lines for flipper are not included in `use_react_native`, where they would normally be under SDK 46 & plugin 46. This is good, as it means we can confirm there's no way the plugin's being included by accident.

I'm not saying iOS autolinking is the culprit, but it definitely looks like it is. I think it's worth trying a build with the exclude set which would block the autolink if found in any of the search paths. I've used the same pattern as you had for `isBuildingDevClient`, and also set your flipper version explicitly to match your package.json.

```ts
const config: ExpoConfig = {
  name: isBuildingDevClient ? 'My App - Dev' : 'My App',
  // ...
  plugins: [
    ...[isBuildingDevClient ? ['expo-community-flipper', '0.173.0'] : null].filter(notEmpty),
    [
      'expo-notifications',
      {
        icon: './assets/notification-icon.png',
        color: '#FFFFFF',
      },
    ],
    'sentry-expo',
  ],
  autolinking: {
    ios: {
      exclude: [
        ...[isBuildingDevClient ? null : "react-native-flipper"].filter(notEmpty),
      ]
    }
  }
}
```

**Comment by SimenB** [comment]
There is no `autolinking` field in `ExpoConfig` (afaict, no mention of `autolink` in the entire `@expo/config` package).

This might be a type error of course, but docs seems to indicate this is only in package.json or directly `Podfile` or `settings.gradle`. https://docs.expo.dev/modules/autolinking/#configuration

Maybe this config plugin needs to update those files if `enabled: false` instead of excluding the plugin altogether?

**Comment by SimenB** [comment]
That said, for science, I've kicked off a build adding the config to package.json, just to verify if autolinking really is the issue or not.

Yesterday our build was in queue for 4 hours - hopefully we'll have an answer sooner today 😅

**Comment by thecodedrift** [comment]
Yeah, I agree I don't see it in the [typings](https://github.com/expo/expo/blob/main/packages/%40expo/config-types/src/ExpoConfig.ts). It may just be an oversight that it reads from package.json instead of app config, especially since it's in the `expo` namespace.

In the meantime, you can always run `npx expo-modules-autolinking resolve --platform ios` and see if it's finding (and autolinking) react-native-flipper. If it finds it, it'll try and link it. That _shouldn't_ be an issue as linking files shouldn't trigger weird imports in AppDelegate, or really anywhere, but it wouldn't be the first time I've been surprised.

**Comment by SimenB** [comment]
Build failed even if excluding it

**Comment by SimenB** [comment]
`npx expo-modules-autolinking resolve --platform ios` only prints `expo-*` modules, so that might be why it makes no difference? 😅

**Comment by thecodedrift** [comment]
Alright. I’ll keep digging in the morning. For now, we can probably remove
it from package.json and confirm that it’s existence alone in package.json
is enough to break a build, which would mean it’s something upstream and we
can open an issue on the main expo repo.

**Comment by thecodedrift** [comment]
FWIW, confirmed I can build without including any "react-native-flipper" / "expo-community-flipper" in the package.json. Obviously that isn't ideal, but I'd love a second confirmation before opening the issue on the expo repo that there's some weird magic going on that can't be turned off.

**Comment by SimenB** [comment]
Confirmation on what? We have successful builds if flipper is not present, but it fails if it's present in `package.json`, but no usage of it. Is that the confirmation, or is there something else you're after? 😅

**Comment by thecodedrift** [comment]
> We have successful builds if flipper is not present, but it fails if it's present in package.json, but no usage of it. 

Exactly that. It's helpful when two people have a minimal reproduction; makes it easier to explain in a bug upstream. I'll link the related issue here as well.

**Comment by SimenB** [comment]
Cool 👍

**Comment by itsramiel** [comment]
Getting this error building a preview build with expo. is this related? 
```
❌  Undefined symbols for architecture arm64
┌─ Symbol: _OBJC_CLASS_$_FlipperClient
└─ Referenced from: objc-class-ref in libreact-native-flipper.a(FlipperReactNativeJavaScriptPluginManager.o)


❌  ld: symbol(s) not found for architecture arm64


❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

packages versions: 
```
"expo-community-flipper": "^47.0.0",
"react-native-flipper": "^0.173.0",
```

**Comment by thecodedrift** [comment]
It's very possible @itsramiel. Are you using expo SDK 47? And if so, when you remove react-native-flipper completely from your package.json, does the app build correctly?

**Comment by thecodedrift** [comment]
From the react native docs: https://github.com/react-native-community/cli/blob/main/docs/autolinking.md

Autolinking, to the best of my understanding...

1. Runs `react-native config` via ruby, which returns JSON about all react-native items with a platform for ios/android (and cares in this case about ios)
2. Adds those dependencies to CocoaPods dev pods
3. Adds build phase scripts if required
4. Continues with the building process

Of course, `react-native-flipper` will get autolinked, as it has a Podspec in its root. Current versions of flipper may require changes to the project that haven't necessarily landed in react-native yet. If you only want the inspector, you can remove `react-native-flipper` and just use the config plugin to enable the default bundled Flipper in development. If you need Flipper plugins, there are two solutions that seem to be working:

* Set `0.125.0` for `react-native-flipper` - This is a known working version of react-native-flipper. Expo SDK47 uses React Native 0.70.5 which uses Flipper **0.125.0** [ref1](https://github.com/facebook/react-native/blob/v0.70.5/scripts/react_native_pods.rb) [ref2](https://github.com/facebook/react-native/blob/v0.70.5/scripts/cocoapods/flipper.rb). It's _ancient_ (last bumped July 6), but it is what's enabled by default and what react-native currently tests against
* If you need a more modern version of the flipper bridge, select a version of `react-native-flipper` tested with react native 0.70.5. `0.164.0` seems to be a downgrade from the latest release that is compatible with react-native 0.70.x [ref](https://github.com/facebook/flipper/issues/4278) due to a possible introduced regression. It appears from the linked issue to be compatible for those actively using it.

Flipper and react-native, while they bundle together, often release on very different cadences. I do wish there was an easy way to read the [flipper file](https://github.com/facebook/react-native/blob/v0.70.5/scripts/cocoapods/flipper.rb) for any given react-native version, but we'll likely have to rely on the react-native upgrade tool to alert us of changes.

<hr />

### Additional References
* https://github.com/facebook/react-native/issues/34005

**Comment by itsramiel** [comment]
> It's very possible @itsramiel. Are you using expo SDK 47? And if so, when you remove react-native-flipper completely from your package.json, does the app build correctly?

I am on expo SDK 47, and I did not try to remove flipper completely. Prior to that I was on expo sdk 46 with flipper on `0.152.0` working fine.

Seeing you last comment, I am trying to create a build with version `0.164.0`. I'll let you know the result

**Comment by itsramiel** [comment]
@jakobo 
expo: 47
expo-community-flipper: 47
react-native-flipper: 0.164.0

seems to build. Did not try to try debugging though

**Comment by hirbod** [comment]
I also had to downgrade from 0.174.0 to 0.164.0. After downgrading I was able to build my release project again.

**Comment by SimenB** [comment]
0.164.0 also works for SDK 46. Flipper is still compiled even without the config plugin present, but I guess that's more an issue with RN and autolinking than this plugin.

**Comment by thecodedrift** [comment]
Glad it's working. It sounds like we're running into the regression from https://github.com/facebook/flipper/issues/4278, where others using react-native-flipper (non-expo) rolled back to 0.163,164.* with success.

Unfortunately, there isn't a quick fix for the autolinking side. IMO the autolink code is doing the right thing; it just sucks that Flipper's moving so quickly that you can accidentally autolink a version of Flipper that doesn't work with your current react-native.

**Comment by rusakovic** [comment]
If someone has the same issue.
Bare workflow
"expo": "^47.0.0",
"react-native": "0.70.5",

 "react-native-flipper": "0.172.0" - working
  "react-native-flipper": "0.174.0" - working
    "react-native-flipper": "0.175.0" - working
    "react-native-flipper": "0.176.0" - not working
  "react-native-flipper": "0.176.1" - not working
  
  
  Podfile
  ```
    use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # 'Flipper' => '0.176.1' should be the same version as in package.json
    :flipper_configuration => FlipperConfiguration.enabled(["Debug"], { 'Flipper' => '0.175.0' }),
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  ```
