### ISSUE TITLE
Broken links in npmjs.com readme

### ISSUE THREAD

**Issue by obasille** [jakobo/expo-community-flipper#5]
Hi,
Just wanted to report that there are a few broken links on the [npm page](https://www.npmjs.com/package/expo-community-flipper):

[Documentation for the master branch](https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/community-flipper.md)

[Documentation for the latest stable release](https://docs.expo.io/versions/latest/sdk/community-flipper/)[](https://www.npmjs.com/package/expo-community-flipper#installation-in-managed-expo-projects)

Installation in [managed](https://docs.expo.io/versions/latest/introduction/managed-vs-bare/) Expo projects

This last one gets redirected to:
https://docs.expo.dev/introduction/managed-vs-bare

**Comment by thecodedrift** [comment]
Thanks for flagging! We were using the default module generated README, and I think it'd be useful to implement our own.

**Comment by thecodedrift** [comment]
Resolved in `44.0.2` https://github.com/jakobo/expo-community-flipper/blob/main/CHANGELOG.md#4402
