### ISSUE TITLE
SDK 47 with v47.0.2 still not working

### ISSUE THREAD

**Issue by luispuig** [jakobo/expo-community-flipper#52]
Hello,

I read other issues about the problem "┌─ Symbol: _OBJC_CLASS_$_FlipperClient
└─ Referenced from: objc-class-ref in libreact-native-flipper.a(FlipperReactNativeJavaScriptPluginManager.o)"

https://github.com/jakobo/expo-community-flipper/issues/49 concludes that using 47.0.2 everything should work. I am actually blocked and I need to make to release :)

I also tried the combinations describe at https://github.com/jakobo/expo-community-flipper/issues/42#issuecomment-1366864224

And bonus track, I tried to upgrade to SDK48 but it is still soon and I ran into some other problems. 

Could someone give me some light, please?

package.json
```
"expo": "47.0.12",
"react-native": "0.70.5",
"expo-community-flipper": "47.0.2",
"react-native-flipper": "0.174.0"
```

app.json
```
"jsEngine": "hermes", // I also tried removing this
 "plugins": [
      ["expo-community-flipper", "0.174.0"],
   ]
```

podfile
```
  use_react_native!(
    :path => config[:reactNativePath],
# @generated begin expo-community-flipper-isprod - expo prebuild (DO NOT MODIFY) sync-828c22a1a38236bf5b7c203393f474bc68356b34
    # ENV value added to support Hermes
    :production => ENV["PRODUCTION"] == "1" ? true : false,
# @generated end expo-community-flipper-isprod
    :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes',
    :fabric_enabled => flags[:fabric_enabled],
# @generated begin expo-community-flipper-urn - expo prebuild (DO NOT MODIFY) sync-36549b284a4a7b839b8dd0b522cfd451d4ff147e
    :flipper_configuration => FlipperConfiguration.enabled(["Debug", "Release"], { 'Flipper' => '0.174.0' }),
# @generated end expo-community-flipper-urn
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    #
    # Uncomment to opt-in to using Flipper
    # Note that if you have use_frameworks! enabled, Flipper will not work
    # :flipper_configuration => !ENV['CI'] ? FlipperConfiguration.enabled : FlipperConfiguration.disabled,
  )
```

I am trying with the command: `expo run:ios --configuration Release`

Thanks in advance

**Comment by luispuig** [comment]
Just in case it can be the problem, I also got as dependency:
```
"redux-flipper": "^2.0.2",
"react-native-flipper-xstate": "1.0.5",
```

**Comment by thecodedrift** [comment]
Roll react-native-flipper back to 163 which is a known working version. https://github.com/facebook/flipper/issues/4278

It is entirely possible something regressed with autolinking & the more recent versions of the flipper package.

**Comment by luispuig** [comment]
It worked, thanks!
