### ISSUE TITLE
No option to remove Flipper for Release

### ISSUE THREAD

**Issue by garrettg123** [jakobo/expo-community-flipper#55]
https://github.com/jakobo/expo-community-flipper/blob/be59f52ffbd4b3f5b0ff201ad48c24c8caec8d4d/plugin/src/withFlipper.ios.ts#L49

Why is Flipper ever included in Release builds?

I'm getting this error in my `eas build`:
```
› Compiling react-native-flipper Pods/react-native-flipper » FlipperReactNativeJavaScriptPluginManager.m

❌  (../node_modules/react-native-flipper/ios/FlipperReactNativeJavaScriptPluginManager.h:12:9)

  10 | #import <React/RCTBridgeModule.h>
  11 | 
> 12 | #import <FlipperKit/FlipperClient.h>
     |         ^ 'FlipperKit/FlipperClient.h' file not found
  13 | 
  14 | NS_ASSUME_NONNULL_BEGIN
  15 | 
› Compiling @segment/analytics-react-native Pods/segment-analytics-react-native » AnalyticsReactNative.swift
```
Is there a way to remove this pod for release? My build works locally with `expo run:ios`

**Comment by Nantris** [comment]
See this comment: https://github.com/jakobo/expo-community-flipper/pull/20#issuecomment-1226528150

**Comment by thecodedrift** [comment]
Thanks Slapbox for catching this while I was out at conferences. @garrettg123, the advice in #20 should be applicable. And if you're on the newest versions of Expo, the [build-properties plugin](https://docs.expo.dev/versions/latest/sdk/build-properties/) now has built in flipper support.

LMK if the issue persists and I'll reopen this.
