### ISSUE TITLE
Should react-native-flipper dependency be specified in package.json?

### ISSUE THREAD

**Issue by Nantris** [jakobo/expo-community-flipper#56]
Or is simply adding `expo-community-flipper` to the project enough?

**Comment by thecodedrift** [comment]
You'll only need to specify `react-native-flipper` if either

* You are using a version of Flipper different than the react native default
* You are using a 3rd party plugin which needs access to RNF as a peer dependency

In most situations, `expo-community-flipper` should be enough. For the latest expo release, you can even just use the official build properties plugin.
