### ISSUE TITLE
iOS builds fail with SDK 48

### ISSUE THREAD

**Issue by Nantris** [jakobo/expo-community-flipper#57]
The error is below. For the profile that's failing, we're not using any customization like `"env": { "FLIPPER_DISABLE": "1" }` so I'm not sure what might cause the problem.

Android builds worked.

```
[stderr] 
Error: [ios.dangerous]: withIosDangerousBaseMod: Cannot add flipper arguments to the project's ios/Podfile. Please report this with a copy of your project Podfile. You can generate this with the `expo prebuild` command.
[stderr] 
Error: [ios.dangerous]: withIosDangerousBaseMod: Cannot add flipper arguments to the project's ios/Podfile. Please report this with a copy of your project Podfile. You can generate this with the `expo prebuild` command.
[stderr] 
    at updatePodfileContentsWithFlipper (/Users/expo/workingdir/build/node_modules/expo-community-flipper/build/withFlipper.ios.js:190:15)
[stderr] 
    at /Users/expo/workingdir/build/node_modules/expo-community-flipper/build/withFlipper.ios.js:82:37
[stderr] 
    at action (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:201:29)
[stderr] 
    at interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:27)
[stderr] 
    at action (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:206:14)
[stderr] 
    at async interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
[stderr] 
    at async interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
[stderr] 
    at async interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
[stderr] 
    at async interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
[stderr] 
    at async action (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/createBaseMod.js:61:21)
[stderr] 
    at async interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
[stderr] 
    at async evalModsAsync (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/mod-compiler.js:204:25)
[stderr] 
    at async Object.compileModsAsync (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/mod-compiler.js:124:10)
[stderr] 
    at async configureProjectAsync (/Users/expo/workingdir/build/node_modules/@expo/cli/build/src/prebuild/configureProjectAsync.js:54:15)
[stderr] 
    at async prebuildAsync (/Users/expo/workingdir/build/node_modules/@expo/cli/build/src/prebuild/prebuildAsync.js:83:9)
[stderr] 
error Command failed with exit code 1.
```

**Comment by danielgangverk** [comment]
I'm having the same issue

**Comment by danielgangverk** [comment]
If I run another iOS build with the recommended app.json configuration from expo mentioned here https://docs.expo.dev/guides/using-flipper/ then everything seems to work.

I removed expo-community-flipper from the "plugins" array.

```json

{
  "plugins": [
    [
      "expo-build-properties",
      {
        "ios": {
          "flipper": true
        }
      }
    ]
  ]
}
```

**Comment by Nantris** [comment]
@jakobo any thoughts on this issue? Is there anything I can provide to help towards resolution?

**Comment by thecodedrift** [comment]
The issue is coming up because the Podfile regex isn't matching. What's your SDK version & are you using expo-community-flipper still?

> Please report this with a copy of your project Podfile. You can generate this with the `expo prebuild` command.

Can I see the `Podfile` from expo's prebuild? I'm betting the flipper arguments moved or the regex isn't finding the right lines to change.

**Comment by Nantris** [comment]
@jakobo I apologize for not including it to begin with - I wasn't sure that message was coming from `expo-community-flipper`. I think this is what you need to see, right?

```
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

platform :ios, podfile_properties['ios.deploymentTarget'] || '13.0'
install! 'cocoapods',
  :deterministic_uuids => false

target 'Project' do
  use_expo_modules!
  config = use_native_modules!

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
# @generated begin expo-community-flipper-isprod - expo prebuild (DO NOT MODIFY) sync-828c22a1a38236bf5b7c203393f474bc68356b34
    # ENV value added to support Hermes
    :production => ENV["PRODUCTION"] == "1" ? true : false,
# @generated end expo-community-flipper-isprod
    :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes',
    :fabric_enabled => flags[:fabric_enabled],
# @generated begin expo-community-flipper-urn - expo prebuild (DO NOT MODIFY) sync-c7cb57ad0548737963234cf3378d4b0e06dca78b
    :flipper_configuration => FlipperConfiguration.enabled(["Debug", "Release"]),
# @generated end expo-community-flipper-urn
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    #
    # Uncomment to opt-in to using Flipper
    # Note that if you have use_frameworks! enabled, Flipper will not work
    # :flipper_configuration => !ENV['CI'] ? FlipperConfiguration.enabled : FlipperConfiguration.disabled,
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end
```

**Comment by thecodedrift** [comment]
the `withIosDangerousBaseMod` is definitely coming from us: https://github.com/jakobo/expo-community-flipper/blob/be59f52ffbd4b3f5b0ff201ad48c24c8caec8d4d/plugin/src/withFlipper.ios.ts#L221 Looking into it now to figure out why the regex is failing

**Comment by thecodedrift** [comment]
Got it. With SDK48, you can use the official build properties plugin instead: https://docs.expo.dev/versions/latest/sdk/build-properties/

I'll add a check internally that looks for the `:flipper_configuration => flipper_config` line and offers a better error message

**Comment by thecodedrift** [comment]
Published 48.0.1 with correct guidance. ❤️  If you're on Expo SDK 48, the build properties plugin is the way to go, as it helps avoid some of the other flipper footguns such as having `use_frameworks` on at the same time. Thanks for the catch @Slapbox!

**Comment by Nantris** [comment]
Thanks again for your great work @jakobo!

I have a few questions, I was wondering if you know the answers?

With SDK 48 we no longer need `expo-community-flipper` and also not need to actually define anything with `expo-build-properties` either? But the docs are confusing because it seems each platform is handled differently.

**[From the docs](https://docs.expo.dev/versions/latest/sdk/build-properties/):**

**Android:**

> By default, Flipper is enabled with the version that comes bundled with react-native.

> Use this to change the [Flipper](https://fbflipper.com/) version when running your app on Android. You can set the flipper property to a semver string and specify an alternate Flipper version.


**iOS:**

> Enable [Flipper](https://fbflipper.com/) when running your app on iOS in Debug mode. Setting true enables the default version of Flipper, while setting a semver string will enable a specific version of Flipper you've declared in your package.json. The default for this configuration is false.

The docs make me think Android has Flipper support by default, even in PROD, but that iOS never has it unless explicitly specified? Does that seem right?

Do you know if there's some way to disable Flipper integration in PROD like was possible with `expo-community-flipper`?

I guess this snippet in our `eas.json` can be removed now too since it's specific to `expo-community-flipper` as far as I know?

```
"env": {
    "FLIPPER_DISABLE": "1"
}
```

**Comment by thecodedrift** [comment]
Hey @Slapbox

> The docs make me think Android has Flipper support by default, even in PROD, but that iOS never has it unless explicitly specified? Does that seem right?

Mostly correct. On Android, React Native only binds Flipper in the debug environment: https://github.com/expo/expo/blob/da782aee0c9a18f79d7ee822bded9d40cb4eb90a/apps/bare-expo/android/app/build.gradle#L161 and there's no way in react-native (without major edits) to enable flipper on Android+Prod,

It's been this way for a while now and while I 100% disagree with the pattern, it makes much more sense for us (and expo) to match the upstream docs to keep maintenance costs down even if it feels like there's different steps for iOS v Android.

> I guess this snippet in our eas.json can be removed now too since it's specific to expo-community-flipper as far as I know?

Correct. If you'd like to control flipper on iOS via an environment variable, you can use `ENV.NO_FLIPPER=1` instead. However, it's iOS specific.
