### ISSUE TITLE
[Docs] Wrong Expo SDK versions?

### ISSUE THREAD

**Issue by wtfabio** [jakobo/expo-community-flipper#7]
https://github.com/jakobo/expo-community-flipper/blob/e3f7e987cc6c8fa62a8f3c74bf0857a9843ef431/README.md?plain=1#L71-L74

Isn't it supposed to be Expo SDKs 43 and 44?

---

Thanks for the amazing blog post regarding Flipper integration with Expo and this package!

**Comment by thecodedrift** [comment]
100% correct. I fat fingered this and will update the readme (and make sure npm reflects the correct info)

**Comment by thecodedrift** [comment]
Resolved in 75eb8ab
